services:
  next:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./twitter:/twitter
    command: sh -c "npm run dev"
    stdin_open: true