version: "3.8"
services:
  frontend:
    build: 
      context: .
      dockerfile: DockerfileFront
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm run dev"
    stdin_open: true
  backend:
    build: 
      context: .
      dockerfile: DockerfileBack
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    command: sh -c "PORT=3001 npm run dev"
